[package]
name = "beamium"
version = "2.0.0"
edition = "2018"
build = "build.rs"
authors = [
  "Kevin Georges <kevin.georges@corp.ovh.com>",
  "Florentin DUBOIS <florentin.dubois@corp.ovh.com>"
]

[dependencies]
bytes = "0.4.12"
config = "0.9.2"
failure = "0.1.5"
futures = "0.1.26"
humanize-rs = "0.1.5"
glob = "0.3.0"
structopt = "0.2.15"
slog-async = "2.3.0"
slog-term = "2.4.0"
slog-scope = "4.1.1"
slog-syslog = "0.11.0"
serde = "1.0.90"
serde_derive = "1.0.90"
regex = "1.1.6"
hyper = "0.12.27"
hyper-rustls = "0.16.1"
tokio = "0.1.19"
time = "0.1.42"
crossbeam = "0.7.1"
warp = "0.1.15"
prometheus = "0.5.0"
lazy_static = "1.3.0"
backoff = "0.1.5"

[dependencies.slog]
version = "2.4.1"
features = ["release_max_level_trace", "max_level_trace"]

[dependencies.ctrlc]
version = "3.1.2"
features = ["termination"]

[build-dependencies]
failure = "0.1.5"
git2 = "0.8.0"
time = "0.1.42"

[profile.release]
lto = true
panic = "abort"

[profile.bench]
lto = true
